export const post_types = {
    UPDATE_POST: 'UPDATE_POST',
    EDIT_POST: 'EDIT_POST',
    FETCH_POST: 'FETCH_POST',
    DELETE_POST: 'DELETE_POST',
    NEW_POST: 'NEW_POST',
    LIKE_POST: 'LIKE_POST',
    COMMENT_POST: 'COMMENT_POST',
  };